# Generated by Django 5.0.6 on 2024-07-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
